variables:
    APP_NAME: 'devops-testtt'
    APP_VERSION: '1'
    APP_OWNER_EMAIL: 'chaoyuege@sohu-inc.com'
    MANUAL_REVIEW: 'false'

include:
    project: 'devops/ci-template-test'
    file:
        - '/maven/gitlab-ci-template.yml'
    ref: master
