variables:
    APP_NAME: 'devops-simple-test'
    APP_VERSION: 'master-46e31069-2502211445-151211'
    APP_OWNER_EMAIL: 'chaoyuege@sohu-inc.com'
    MANUAL_REVIEW: 'true'

include:
    project: 'devops/ci-templates'
    file:
        - '/maven/gitlab-ci-template.yml'
    ref: master
